### ISSUE TITLE
Need a way to minimize the code

### ISSUE THREAD

**Issue by dong77** [Loopring/loopring.js#18]

**Comment by BenjaminPrice** [comment]
Already added in `refactor` branch

**Comment by dong77** [comment]
We need to use grant to manage tasks, not using gen.sh. https://github.com/Loopring/loopring.js/pull/20 is only halfway through.

**Comment by BenjaminPrice** [comment]
I am going to try and get it working with webpack to try and get it smaller than what we can do with browserify. Should be possible in part with the migration from bower to yarn and the dependency flattening.

**Comment by dong77** [comment]
You are the man!

**Comment by BenjaminPrice** [comment]
Resolved by #28
