### ISSUE TITLE
Discussion: Tests

### ISSUE THREAD

**Issue by BenjaminPrice** [Loopring/loopring.js#5]
Before we get too far into the work on this repository, I would like to recommend we use `Jest` (by Facebook) instead of `Mocha`. It's a simpler architecture, supports typescript (with `ts-jest`), and is much faster. It natively supports parallel test streams as well as code coverage and can also learn from previous test runs. If a test failed on a previous run, it will be smart and run that test first on the next test run; it will also use previous test runs to determine how best to parallelize tests.

https://facebook.github.io/jest/

**Comment by lyon-liao** [comment]
@BenjaminPrice It's Ok for me. And I will add `Jest` to project later.

**Comment by BenjaminPrice** [comment]
I am closing this issue. I will add jest for tests as I set up the initial logic in here.
